name: Deploy to AWS - PROD for NI_BE_TASKS

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-backend:
    runs-on: ubuntu-20.04

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}

    -   name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push the Docker image
      run: |
        docker build . -t ${{ secrets.DOCKERHUB_REPO }}:$GITHUB_SHA 
        docker push ${{ secrets.DOCKERHUB_REPO }}:$GITHUB_SHA
